version: "3"

services:

  application:

    image: docker-api-demo
    container_name: docker-api-demo-container

    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "8085:8085"